version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: final-ai-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # command:
    #   - xvfb-run
    #   - -a
    #   - --server-args=-screen 0 1280x1024x24
    #   - uvicorn
    #   - app.main:app
    #   - --host
    #   - 0.0.0.0
    #   - --port
    #   - "8000"
    #   - --reload
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
